export const userInfoSql =  `WITH
	GRUPOS_USUARIOS AS (
		SELECT
			G.ID,
			G.DESCRIPCION,
			USG.ID_USUARIO
		FROM
			GRUPOS G
			LEFT JOIN USUARIOS_GRUPOS USG ON USG.ID_GRUPO = G.ID
	)
SELECT
	US.ID,
	US.NOMBRE,
	US.APELLIDO,
	IS_SUPER_ADMIN AS ISA,
	VERIFICADO AS VFD,
	COALESCE(
		JSONB_AGG(
			JSONB_BUILD_OBJECT('id', GUS.ID, 'descripcion', GUS.DESCRIPCION)
			ORDER BY
				GUS.ID
		) FILTER (
			WHERE
				GUS.ID IS NOT NULL
		),
		'[]'::JSONB
	) AS GRUPOS
FROM
	USUARIOS US
	LEFT JOIN GRUPOS_USUARIOS GUS ON GUS.ID_USUARIO = US.ID
WHERE
	US.ACTIVO = TRUE
	AND US.ID = $1
GROUP BY
	US.ID,
	US.NOMBRE,
	US.APELLIDO,
	IS_SUPER_ADMIN
`