export const consultaParticipacionByUsuario:string = `
WITH
	INFO_META AS (
		SELECT
			PEM.PRECIO_META,
			PEM.NOMBRE_META
		FROM
			PARTICIPACION_EMPRESA PEM
		LIMIT
			1
	),
	INFO_USUARIO_GANANCIAS AS (
		SELECT
			U.ID AS ID_USUARIO,
			SUM(
				CASE
					WHEN GF.ACTIVO = TRUE THEN GF.MONTO
				END
			) AS GANANCIAS_TOTALES,
			SUM(
				CASE
					WHEN GF.ACTIVO = TRUE
					AND GF.ID_ESTADO = 1 THEN GF.MONTO
				END
			) AS GANANCIAS_POR_COBRAR,
			SUM(
				CASE
					WHEN GF.ACTIVO = TRUE
					AND GF.ID_ESTADO = 2 THEN GF.MONTO
				END
			) AS GANANCIAS_COBRADAS
		FROM
			USUARIOS U
			JOIN GANANCIAS_FUTURAS GF ON GF.ID_USUARIO = U.ID
		GROUP BY
			U.ID
	),
	SUSCRIPCIONES_PLATAFORMA_CONTEO AS (
		SELECT
			SUM(
				CASE
					WHEN SU.ESTADO = 1
					AND ACTIVO = TRUE THEN 1
				END
			) AS CANTIDAD_SUSCRIPCIONES_PENDIENTES,
			SUM(
				CASE
					WHEN SU.ESTADO = 2
					AND ACTIVO = TRUE THEN 1
				END
			) AS CANTIDAD_SUSCRIPCIONES_ACTIVAS,
			SUM(
				CASE
					WHEN SU.ESTADO = 3
					AND ACTIVO = TRUE THEN 1
				END
			) AS CANTIDAD_SUSCRIPCIONES_SUSPENDIDAS
		FROM
			SUSCRIPCIONES SU
	)
SELECT
	COM.ID,
	COM.ID_USUARIO,
	COM.TOTAL_META,
	COM.PORCENTAJE_PARTICIPACION,
	COALESCE(
		(
			SELECT
				SC.CANTIDAD_SUSCRIPCIONES_PENDIENTES
			FROM
				SUSCRIPCIONES_PLATAFORMA_CONTEO SC
		),
		0
	) AS CANTIDAD_SUSCRIPCIONES_PENDIENTES,
	COALESCE(
		(
			SELECT
				SC.CANTIDAD_SUSCRIPCIONES_ACTIVAS
			FROM
				SUSCRIPCIONES_PLATAFORMA_CONTEO SC
		),
		0
	) AS CANTIDAD_SUSCRIPCIONES_ACTIVAS,
	COALESCE(
		(
			SELECT
				SC.CANTIDAD_SUSCRIPCIONES_SUSPENDIDAS
			FROM
				SUSCRIPCIONES_PLATAFORMA_CONTEO SC
		),
		0
	) AS CANTIDAD_SUSCRIPCIONES_SUSPENDIDAS,
	(
		SELECT
			PRECIO_META
		FROM
			INFO_META
	) AS PRECIO_ACTUAL,
	SUM(
		CASE
			WHEN DET.ACTIVO = TRUE
			AND DET.ESTADO = 1 THEN DET.TOTAL_VENTA
			ELSE 0
		END
	) AS TOTAL_INVERTIDO,
	COALESCE(GUF.GANANCIAS_TOTALES, 0) AS GANANCIAS_TOTALES,
	COALESCE(GUF.GANANCIAS_POR_COBRAR, 0) AS GANANCIAS_POR_COBRAR,
	COALESCE(GUF.GANANCIAS_COBRADAS, 0) AS GANANCIAS_COBRADAS,
	COALESCE(
		JSON_AGG(
			JSON_BUILD_OBJECT(
				'id',
				DET.ID,
				'monto_meta',
				DET.MONTO_META,
				'id_moneda',
				DET.ID_MONEDA,
				'total_venta',
				DET.TOTAL_VENTA
			)
		) FILTER (
			WHERE
				DET.ACTIVO = TRUE
				AND DET.ESTADO = 1
		),
		'[]'::JSON
	) AS DETALLES_COMPRAS
FROM
	COMPRAS_PARTICIPANTES COM
	LEFT JOIN COMPRAS_DETALLES_PARTICIPANTES DET ON DET.ID_COMPRAS_PARTICIPANTES = COM.ID
	LEFT JOIN INFO_USUARIO_GANANCIAS GUF ON GUF.ID_USUARIO = COM.ID_USUARIO
WHERE
	COM.ID_USUARIO = $1
GROUP BY
	COM.ID,
	GUF.GANANCIAS_TOTALES,
	GUF.GANANCIAS_POR_COBRAR,
	GUF.GANANCIAS_COBRADAS;
`


export const consultaparticipantes = `with INFO_USUARIO_GANANCIAS AS (
		SELECT
			U.ID AS ID_USUARIO,
			SUM(
				CASE
					WHEN GF.ACTIVO = TRUE THEN GF.MONTO
				END
			) AS GANANCIAS_TOTALES,
			SUM(
				CASE
					WHEN GF.ACTIVO = TRUE
					AND GF.ID_ESTADO = 1 THEN GF.MONTO
				END
			) AS GANANCIAS_POR_COBRAR,
			SUM(
				CASE
					WHEN GF.ACTIVO = TRUE
					AND GF.ID_ESTADO = 2 THEN GF.MONTO
				END
			) AS GANANCIAS_COBRADAS
		FROM
			USUARIOS U
			JOIN GANANCIAS_FUTURAS GF ON GF.ID_USUARIO = U.ID
		GROUP BY
			U.ID
	)

SELECT
	u.id,
	(U.NOMBRE || U.APELLIDO) AS NOMBRE,
	u.telefono,
	u.documento,
	u.email,
	CPAR.TOTAL_META AS TOTAL_META_COMPRADA,
	CPAR.PORCENTAJE_PARTICIPACION,
	COALESCE(GUF.GANANCIAS_TOTALES, 0) AS GANANCIAS_TOTALES,
	COALESCE(GUF.GANANCIAS_POR_COBRAR, 0) AS GANANCIAS_POR_COBRAR,
	COALESCE(GUF.GANANCIAS_COBRADAS, 0) AS GANANCIAS_COBRADAS,
	COALESCE(
		JSON_AGG(
			JSON_BUILD_OBJECT(
				'id',
				DETCOM.ID,
				'monto_meta',
				DETCOM.MONTO_META,
				'id_moneda',
				DETCOM.ID_MONEDA,
				'total_venta',
				DETCOM.TOTAL_VENTA,
				'fecha_compra',
				detcom.fecha_creacion
				
			)
		) FILTER (
			WHERE
				DETCOM.ACTIVO = TRUE
				AND DETCOM.ESTADO = 1
		),
		'[]'::JSON
	) AS DETALLES_COMPRAS
FROM
	USUARIOS U
	JOIN USUARIOS_GRUPOS USG ON USG.ID_USUARIO = U.ID
	AND USG.ID_GRUPO = 4
	JOIN COMPRAS_PARTICIPANTES CPAR ON CPAR.ID_USUARIO = USG.ID_USUARIO
	JOIN COMPRAS_DETALLES_PARTICIPANTES DETCOM ON DETCOM.ID_COMPRAS_PARTICIPANTES = CPAR.ID
	join INFO_USUARIO_GANANCIAS guf on guf.id_usuario = u.id
GROUP BY
	U.ID,
	U.NOMBRE,
	U.APELLIDO,
	CPAR.TOTAL_META,
	CPAR.PORCENTAJE_PARTICIPACION,
	GANANCIAS_TOTALES,
	GANANCIAS_POR_COBRAR,
	GANANCIAS_COBRADAS`